# Generated by Django 3.2.4 on 2022-11-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='orders',
            field=models.ManyToManyField(related_name='food_items', through='foodDelivery.OrderFoodItem', to='foodDelivery.Order'),
        ),
    ]
